# Generated by Django 3.2.6 on 2021-09-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='hours',
        ),
    ]
